name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: bright-sparrow-38 # the name of the project on Deno Deploy
          entrypoint: api/main.ts # the entrypoint to deploy
